---
- name: Kubernetes Node Setup
  hosts: node
  become: yes

  vars:
    kube_repo_url: "https://pkgs.k8s.io/core:/stable:/v1.29/rpm/"
    kube_repo_key: "https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key"
    kube_version: "1.29.9"
    kube_token: "jmkcx8.t63mxfd3t9iwlfed"
    kube_ca_hash: "sha256:747136993e8e544eba5b00cdf7c577cff3663760110c5b397c995ababb8868a6"
    kube_master_ip: "192.168.1.101"
    kube_node_name: "node1"

  tasks:
    - name: Load br_netfilter kernel module
      command: modprobe br_netfilter
      args:
        warn: false

    - name: Enable bridge-nf-call-iptables
      shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

    - name: Ensure containerd.conf exists with correct content
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay kernel module
      command: modprobe overlay
      args:
        warn: false

    - name: Reload br_netfilter module
      command: modprobe br_netfilter
      args:
        warn: false

    - name: Configure Kubernetes yum repository
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl={{ kube_repo_url }}
          enabled=1
          gpgcheck=1
          repo_gpgcheck=0
          gpgkey={{ kube_repo_key }}
          exclude=kubelet kubeadm kubectl

    - name: Install Kubernetes components
      yum:
        name:
          - kubelet-{{ kube_version }}
          - kubeadm-{{ kube_version }}
          - kubectl-{{ kube_version }}
        state: present
        disable_excludes: kubernetes

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted

    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: true

    - name: Configure sysctl settings for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Join Kubernetes cluster
      shell: |
        kubeadm join {{ kube_master_ip }}:6443 --v=5 --node-name={{ kube_node_name }} \
        --token {{ kube_token }} --discovery-token-ca-cert-hash {{ kube_ca_hash }}
      register: join_output
      ignore_errors: true

    - name: Debug join output
      debug:
        var: join_output.stdout
