apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
spec:
  type: NodePort
  ports:
    - name: ipslog
      nodePort: 30094
      port: 9004
      protocol: UDP
      targetPort: 9004
    - name: epplog
      nodePort: 30097
      port: 9007
      protocol: UDP
      targetPort: 9007
    - name: fwlog
      nodePort: 30099
      port: 9009
      protocol: UDP
      targetPort: 9009
  selector:
    app: logstash-logstash
